/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.msaa.view.pendamping;

import com.mysql.jdbc.Connection;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.koneksi;
import model.pendamping;

/**
 *
 * @author ABD, Qohar Agus Maulana (18650051)
 * @author Rizki Fitriani (18650053)
 * @author Annisa Rizkiana Putri (18650048)
 * @author Nisa Kholifatul Ummah (18650065)
 */
public class FormTahsinPendamping extends javax.swing.JFrame {

    Dimension layar = Toolkit.getDefaultToolkit().getScreenSize();
    private DefaultTableModel model = new DefaultTableModel();
    private String pathfile;

    /**
     * Creates new form Tahsin
     */
    public FormTahsinPendamping() {
        initComponents();
        lokasi();
        model();
        getdata();
        btn_importfile.setEnabled(true);

        setTitle("MSAA Application"); 
    }

    protected void lokasi() {
        int x = layar.width / 2 - this.getSize().width / 2;
        int y = layar.height / 2 - this.getSize().height / 2;
        setLocation(x, y);
        txt_mabna.setText(pendamping.getMabna());
    }

    public void model() {

        model = new DefaultTableModel();
        tabel_tahsin.setModel(model);
        model.addColumn("id Tahsin");
        model.addColumn("NIM");
        model.addColumn("Nama");
        model.addColumn("Bulan");
        model.addColumn("Juz");
        model.addColumn("Surat");
        model.addColumn("Ayat");

    }
    public void getdata(){
        try {
            model();
            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet data = stmt.executeQuery("select T.no_tahsin, T.bulan, T.juz, T.surat, T.ayat, T.nim_mhs, M.nama from tahsin T natural join mahasantri M natural join mabna N where T.nim_mhs = M.nim_mahasantri and M.kode_mab = N.kode_mab and N.nama_mab = '"+txt_mabna.getText()+"'");

            while (data.next()) {
                Object[] obj = new Object[7];
                obj[0] = data.getString("T.no_tahsin");
                obj[1] = data.getString("T.nim_mhs");
                obj[2] = data.getString("M.nama");
                obj[3] = data.getString("T.bulan");
                obj[4] = data.getString("T.juz");
                obj[5] = data.getString("T.surat");
                obj[6] = data.getString("T.ayat");

                model.addRow(obj);

            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cm_bulan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_juz = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        txt_surah = new javax.swing.JTextField();
        txt_ayat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_tahsin = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txt_mabna = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btn_importfile = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("NIM");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        txt_nim.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(txt_nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 183, -1));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Juz/Surat/Ayat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("Tahsin");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 95, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Bulan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        cm_bulan.setBackground(new java.awt.Color(255, 255, 255));
        cm_bulan.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        cm_bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        getContentPane().add(cm_bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 137, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton1.setText("Cari");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 116, -1));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton4.setText("Hapus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 95, -1));

        txt_juz.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(txt_juz, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 57, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 95, -1));

        txt_surah.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(txt_surah, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 57, -1));

        txt_ayat.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        getContentPane().add(txt_ayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 57, -1));

        tabel_tahsin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Kelas", "Mahad", "Lantai", "Kamar", "Juz", "Surat", "ayat", "Kelancaran", "Fashohah", "Tajwid"
            }
        ));
        tabel_tahsin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_tahsinMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_tahsin);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 232, 1110, 330));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("Mahad");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, -1, -1));

        txt_mabna.setBackground(new java.awt.Color(255, 255, 255));
        txt_mabna.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txt_mabna.setText("jLabel2");
        getContentPane().add(txt_mabna, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, -1, -1));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton6.setText("Segarkan");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 116, -1));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton7.setText("Simpan");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 95, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jButton5.setText("Pilih File CSV");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 120, -1));

        btn_importfile.setBackground(new java.awt.Color(255, 255, 255));
        btn_importfile.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btn_importfile.setText("Import File");
        btn_importfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importfileActionPerformed(evt);
            }
        });
        getContentPane().add(btn_importfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 116, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/10tahsin.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 600));

        txt_id.setBackground(new java.awt.Color(255, 255, 255));
        txt_id.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        txt_id.setText("0");
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 102, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new FormPendamping().setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        model();
        getdata();
        txt_id.setText(null);
        txt_ayat.setText(null);
        txt_juz.setText(null);
        txt_nim.setText(null);
        txt_surah.setText(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        try {

            PreparedStatement statement = koneksi.koneksiDB().prepareStatement(
                    "insert into tahsin values (null,?,?,?,?,?)");

            statement.setString(1, cm_bulan.getSelectedItem().toString());
            statement.setString(2, txt_juz.getText());
            statement.setString(3, txt_surah.getText());
            statement.setString(4, txt_ayat.getText());
            statement.setString(5, txt_nim.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Baru telah di tambahkan");

            model();
            txt_ayat.setText(null);
            txt_id.setText(null);
            txt_juz.setText(null);
            txt_nim.setText(null);
            txt_surah.setText(null);
            getdata();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "gagal menambah Data");
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            model();
            Connection conn = (Connection) koneksi.koneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet data = stmt.executeQuery("select T.no_tahsin, T.bulan, T.juz, T.surat, T.ayat, T.nim_mhs, M.nama from tahsin T natural join mahasantri M natural join mabna N where T.nim_mhs = M.nim_mahasantri and M.kode_mab = N.kode_mab and N.nama_mab = '"+txt_mabna.getText()+"' and T.nim_mhs like '%" + txt_nim.getText() + "%' and T.bulan = '" + cm_bulan.getSelectedItem().toString() + "'");

            while (data.next()) {
                Object[] obj = new Object[7];
                obj[0] = data.getString("T.no_tahsin");
                obj[1] = data.getString("T.nim_mhs");
                obj[2] = data.getString("M.nama");
                obj[3] = data.getString("T.bulan");
                obj[4] = data.getString("T.juz");
                obj[5] = data.getString("T.surat");
                obj[6] = data.getString("T.ayat");

                model.addRow(obj);

            }
        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {

            PreparedStatement statement = koneksi.koneksiDB().prepareStatement(
                    "delete from tahsin where no_tahsin =?");

            statement.setString(1, txt_id.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di Hapus");
            model();
            txt_id.setText(null);
            txt_ayat.setText(null);
            txt_juz.setText(null);
            txt_nim.setText(null);
            txt_surah.setText(null);
            getdata();
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {
            PreparedStatement statement = koneksi.koneksiDB().prepareStatement(
                    "update tahsin set bulan = ? ,juz = ? ,surat = ? ,ayat = ?, nim_mhs = ? where no_tahsin = ?");

            statement.setString(1, cm_bulan.getSelectedItem().toString());
            statement.setString(2, txt_juz.getText());
            statement.setString(3, txt_surah.getText());
            statement.setString(4, txt_ayat.getText());
            statement.setString(5, txt_nim.getText());
            statement.setString(6, txt_id.getText());
            statement.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
            model();
            txt_id.setText(null);
            txt_ayat.setText(null);
            txt_juz.setText(null);
            txt_nim.setText(null);
            txt_surah.setText(null);
            getdata();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooseFile = new JFileChooser();
        chooseFile.showOpenDialog(null);
        File file = chooseFile.getSelectedFile();
        pathfile = file.getAbsolutePath();
        btn_importfile.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btn_importfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importfileActionPerformed
        // TODO add your handling code here:
        try {
            BufferedReader br = new BufferedReader(new FileReader(pathfile));
            String line;
            int pas = 0;
            while ((line = br.readLine()) != null) {

                String[] value = line.split(",");
                String sql = "insert into tahsin values (null,?,?,?,?,?)";
                java.sql.Connection conn = (java.sql.Connection) koneksi.koneksiDB();
                PreparedStatement stmt = conn.prepareStatement(sql);

                if (pas == 0) {
                    pas = 1;
                } else {
                    stmt.setString(1, value[0]);
                    stmt.setString(2, value[1]);
                    stmt.setString(3, value[2]);
                    stmt.setString(4, value[3]);
                    stmt.setString(5, value[4]);
                    stmt.executeUpdate();
                    stmt.close();
                    
                    
                }

            }

            br.close();
            JOptionPane.showMessageDialog(null, "Import data berhasil !");
            btn_importfile.setEnabled(false);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e);
            e.printStackTrace();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btn_importfileActionPerformed

    private void tabel_tahsinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_tahsinMouseClicked
        // TODO add your handling code here:
        try {

            int row = tabel_tahsin.rowAtPoint(evt.getPoint());
            if (row > -1) {
                txt_id.setText(tabel_tahsin.getValueAt(row, 0).toString());
                txt_nim.setText(tabel_tahsin.getValueAt(row, 1).toString());
                cm_bulan.setSelectedItem(tabel_tahsin.getValueAt(row, 3).toString());
                txt_juz.setText(tabel_tahsin.getValueAt(row, 4).toString());
                txt_surah.setText(tabel_tahsin.getValueAt(row, 5).toString());
                txt_ayat.setText(tabel_tahsin.getValueAt(row, 6).toString());
                
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tabel_tahsinMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTahsinPendamping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTahsinPendamping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTahsinPendamping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTahsinPendamping.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTahsinPendamping().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_importfile;
    private javax.swing.JComboBox<String> cm_bulan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_tahsin;
    private javax.swing.JTextField txt_ayat;
    private javax.swing.JLabel txt_id;
    private javax.swing.JTextField txt_juz;
    private javax.swing.JLabel txt_mabna;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JTextField txt_surah;
    // End of variables declaration//GEN-END:variables
}
